### PR TITLE
Qos version 2

### PR DESCRIPTION
**Pull request by francislin12**
add qos protocol

### CODE REVIEW

**Review by joenpera — CHANGES_REQUESTED** [review]
Do not merge directly to main.

**Comment by mbaddeley** [comment]
Closing as is trying to merge into main rather than mesh_comm_1.0

**Comment by joenpera** [comment]
> Closing as is trying to merge into main rather than mesh_comm_1.0

Don't merge directly to main.

**Comment by mbaddeley** [comment]
This is why it's getting closed :P

**Pull request closed without merging**
