### PR TITLE
Update OSF test script to check for and use latest IPv6 addressing scheme

### PR DESCRIPTION
**Pull request by mbaddeley**
Minor update to stop using the old fd0X addressing and start using the IPv6 address assigned to tun0.

### CODE REVIEW

**Review by Hiihtaja77 — COMMENTED** [review]
# Use ping6 to ping the IP address fd02::1 over the tun0 interface
obsolete comment ?

Hardcoded prefix fde3:  . Tun0 can any other one from recommended list ( 15 variants)
Can it be done in any other way ?

**Comment by mbaddeley** [comment]
> # Use ping6 to ping the IP address fd02::1 over the tun0 interface
> obsolete comment ?
> 
> Hardcoded prefix fde3: . Tun0 can any other one from recommended list ( 15 variants) Can it be done in any other way ?

I've removed the comment reference to fd02::1, but I think looking at the fde3 address is fine, right? This is agreed as the prefix for OSF.

**Comment by Hiihtaja77** [comment]
In best case you should be able to extract this long address, modify it to node address and ping Node not Host.
but it can be 2 global addresses e.g 2001:db8: can be added for R&D
 May be have sense to extract first global address from tun0 what is not equal to 2001:db8
and use it to ping Host ( Node have other address)

**Review by Hiihtaja77 — COMMENTED** [review]
ok

**Review by Hiihtaja77 — APPROVED** [review]

**Comment by mbaddeley** [comment]
OK, redone the test to use slipcmd to get the node IP. Need to stop and start osf for this to stop slipcmd jamming tunslip6 (thanks @Hiihtaja77 for the tip). Tested with latest image as of 19/12/23 and passes.

**Review by ZAbidTii — APPROVED** [review]

**Pull request merged**
