### PR TITLE
Pytorch package installation

### PR DESCRIPTION
**Pull request by dania-tii**
Installing torch-1.13.1
- This package is required for jamming avoidance and LDPI (IDS)
- It cannot be installed via buildroot as the source code is not available

### CODE REVIEW

**Review by martin-tii — APPROVED** [review]

**Review by joenpera — CHANGES_REQUESTED** [review]
includes only aarch64 installation packages.

**Comment by dania-tii** [comment]
> includes only aarch64 installation packages.

I updated the code such that the installation of pytorch occurs for linux os. The IDS and jamming avoidance features, which require the pytorch package, for now are intended to be enabled only for CM4 platform.

**Comment by joenpera** [comment]
I was thinking that should we have this installation process before entrypoint_nats.sh is called and actually in mesh_start.sh.   As now we are starting all processes and after that installing dependencies.

**Review by joenpera — CHANGES_REQUESTED** [review]
Same was added already as comment:
I was thinking that should we have this installation process before entrypoint_nats.sh is called and actually in mesh_start.sh? As now we are starting all processes and after that installing dependencies.

**Comment by dania-tii** [comment]
> Same was added already as comment: I was thinking that should we have this installation process before entrypoint_nats.sh is called and actually in mesh_start.sh? As now we are starting all processes and after that installing dependencies.

ok, I'll close this pr then and install the dependencies via mesh_start.sh

**Review by joenpera — APPROVED** [review]

**Pull request merged**
