### PR TITLE
The source file 

### PR DESCRIPTION
**Pull request by francislin12**
I have just changed the source of the configuration file

### CODE REVIEW

**Comment by francislin12** [comment]
I have just added the source of the configuration file

**Comment by joenpera** [comment]
Which interface you are planning to use for olsr?  This file is only starting black interface wifi and that will be used later for cbma.

**Comment by francislin12** [comment]
@joenpera all interfaces

**Review by joenpera — CHANGES_REQUESTED** [review]
This don't add any functionality as sourced functions are not called.

Prpbably proper OLSRController Class python implementation needed for olsr control.  Similar which was done for CBMA (CBMAController).   Then that functionality can be integrated to MDM side.

**Comment by saauvine** [comment]
Closing as not valid

**Pull request closed without merging**
