### PR TITLE
SECO-7217: halow should be black interface for multi-radio routing to…

### PR DESCRIPTION
**Pull request by murugesan-kumar**
"If Halow is designated as the white interface and WiFi as the black interface, the Batman V routing with expected throughput will not function smoothly. This is because WiFi's expected throughput will always be 1 (at bat1) due to the stacked interfaces (lower + upper CBMA), while Halow will provide the actual throughput. As a result, traffic will consistently be routed through the Halow interface. To address this, we need to designate Halow as a black interface, similar to WiFi."

### CODE REVIEW

**Review by KavinKumarTN — APPROVED** [review]
Changes are fine in Multi-radio context.

**Review by TIISR — APPROVED** [review]
Makes sense :)

**Review by joenpera — DISMISSED** [review]
wrong target branch

**Comment by murugesan-kumar** [comment]
> wrong target branch

changed to develop. thank you

**Review by TIISR — APPROVED** [review]

**Review by saauvine — APPROVED** [review]

**Comment by murugesan-kumar** [comment]
> wrong target branch
changed to develop

**Review by joenpera — APPROVED** [review]

**Pull request merged**
