### PR TITLE
Setup fastrtps profile with mesh whitelisting address

### PR DESCRIPTION
**Pull request by jnippula**
ROS2 data distribution system discovery mechanism publishes topic
information by default to all network interfaces available in the
system. To avoid that the fastrtps profile needs to be updated to
define ip addresses for the interfaces allowed to be used for ROS2
topic communication.

### CODE REVIEW

**Comment by jnippula** [comment]
There is related PR for fogsw_config providing the setup script:
https://github.com/tiiuae/fogsw_configs/pull/10

**Review by maseabunikie — APPROVED** [review]
Looks good.

**Comment by jnippula** [comment]
Let's delay this change until we get more bandwidth to the mesh. With current low bandwidth mesh network we don't want to allow high ros2 topic message traffic to overload the mesh that would jam also the local ROS2 communication causing very high cpu load and loss of messages in critical topics.

**Comment by joenpera** [comment]
We have delivery practice as follows: "own branch" -> develop -> main (no direct commits)

**Review by joenpera — CHANGES_REQUESTED** [review]
This pull request needs to done to develop branch ( when decided to take in use ).

**Pull request closed without merging**
