### PR TITLE
Add Ethernet-bridge support for QoS-OLSR

### PR DESCRIPTION
**Pull request by francislin12**
I have done some changes based on the comments. This PR is focused on QoS-OLSR Ethernet bridging without NATS for 1.5 and 1.0 MS versions. Others changes have be done and I will make the PR of them. 
The changes can be summarized as follows:
1. created a config file for QoS-OLSR
2. added another if condition in case of some typos while writing a routing protocol 
3. fixed some typos for the mesh.conf

### CODE REVIEW

**Comment by mbaddeley** [comment]
Duplicate of #310 

Let's review this as is - focusing on the integration with 1.0/1.5 (not NATS) at this point.

**Review by mbaddeley — APPROVED** [review]
@

**Comment by mbaddeley** [comment]
@joenpera quick sanity check - there's nothing in the new NATS configuration that uses `bridge_settings.sh` is there? I don't believe so but before I go ahead and approve a merge...

My thinking is as follows. These changes support eth bridge in 1.5 and 1.0, without impacting NATS + 2.0. We should therefore merge this PR without too much complaint as long as @francislin12 confirms he has tested on 1.5 (he has, and it works) so that at least there is some form of QoS-OLSR in develop (even if it is for 1.5/1.0). I know there's some IPv6 stuff randomly in there, plus the configuration probably isn't done in the nicest manner but at lease the feature is then merged.

The next task would then be of course moving QoS-OLSR to 2.0 in a **clean and proper way**.

Thoughts?

**Comment by joenpera** [comment]
> @joenpera quick sanity check - there's nothing in the new NATS configuration that uses `bridge_settings.sh` is there? I don't believe so but before I go ahead and approve a merge...
> 
> My thinking is as follows. These changes support QoS-OLSR eth bridge in 1.5 and 1.0, without impacting NATS + 2.0. We should therefore merge this PR without too much complaint as long as @francislin12 confirms he has tested on 1.5 (he has, and it works) so that at least there is some form of QoS-OLSR in develop (even if it is for 1.5/1.0). I know there's some IPv6 stuff randomly in there, plus the configuration probably isn't done in the nicest manner but at lease the feature is then merged.
> 
> The next task would then be of course moving QoS-OLSR to 2.0 in a **clean and proper way**.
> 
> Thoughts?

Current develop comms controller (NATS) is not using bridge_settings.sh.    Later MS2.0 should implement bridge and routing and those will be removed from comms controller.  From that point comms controller just controls radio resource and starts 11s.

**Review by joenpera — APPROVED** [review]
Not touching NATS/comms controller.

**Pull request merged**
