### PR TITLE
Feature/sec os docker

### PR DESCRIPTION
**Pull request by govindsi**
Code refactoring for secOS docker container using mesh_com_1.0.
This is RFC only, which needs to be merged later once secOS changes are mainlined.

### CODE REVIEW

**Comment by govindsi** [comment]
Backward compatibility : TBD: next patch set

**Comment by joenpera** [comment]
Cryptolib handling? In-Device build or built in secOS or something else?  Now it seems to build from configure.sh script and is it good idea to have make tools inside device.

**Comment by govindsi** [comment]
> Cryptolib handling? In-Device build or built in secOS or something else? Now it seems to build from configure.sh script and is it good idea to have make tools inside device.

This is pre-installed in system image as part of ecies br2_ext build root package. Configure.sh is just having placeholder WAR as there was one missing make install rule, it will be removed once ecies br2_ext  package gets integrated in mainline with all fixes.

**Review by martin-tii — APPROVED** [review]

**Review by joenpera — APPROVED** [review]

**Comment by govindsi** [comment]
Merging to dev branch.
Minor fixes will be done later.

**Pull request merged**
