### PR TITLE
mesh_com: Fix STA connection issue post mesh configuration

### PR DESCRIPTION
**Pull request by govindsi**
IBSS and sta interface are not supported concurrently
with most of single radio(phyx). In order to allow sta
connection post mesh service is running, stop mesh(IBSS)
service on the selected interface if already running.

Signed-off-by: Govind Singh <govind@ssrc.tii.ae>

### CODE REVIEW

**Review by joenpera — CHANGES_REQUESTED** [review]
pull-request done to wrong branch. Make pull requests to develop

**Comment by govindsi** [comment]
Raised pull request on develop.

**Comment by govindsi** [comment]
https://github.com/tiiuae/mesh_com/pull/60

**Comment by govindsi** [comment]
Closing this pull req as its raised on incorrect branch.

**Pull request closed without merging**
